#!/usr/bin/env python3
"""Repo bootstrapper for noctics-core.

This script prepares a local development environment in a repeatable way:
- Verifies Python version support.
- Creates or refreshes the project virtual environment.
- Installs project and development dependencies.
- Ensures default configuration files and runtime directories exist.

It is safe to run multiple times; existing files are left untouched unless you
ask for a rebuild via the CLI flags.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VENV = REPO_ROOT / ".venv"
REQUIREMENTS_FILE = REPO_ROOT / "requirements.txt"
PYPROJECT_FILE = REPO_ROOT / "pyproject.toml"
ENV_FILE = REPO_ROOT / ".env"
CONFIG_EXAMPLE = REPO_ROOT / "config" / "central.example.json"
CONFIG_TARGET = REPO_ROOT / "config" / "central.json"

DEFAULT_ENV_TEMPLATE = dedent(
    """
    # Auto-generated by scripts/bootstrap.py
    NOX_LLM_URL=http://127.0.0.1:11434/api/chat
    NOX_LLM_MODEL=noxllm-05b:latest
    # NOX_HELPER_AUTOMATION=0
    # NOX_DEV_NAME=Rei
    # NOCTICS_PROJECT_NAME=Noctics
    """
).strip() + "\n"

RUNTIME_DIRECTORIES = [
    REPO_ROOT / "memory",
    REPO_ROOT / "memory" / "sessions",
    REPO_ROOT / "memory" / "early-archives",
    REPO_ROOT / "datasets",
    REPO_ROOT / "models",
]


class BootstrapError(RuntimeError):
    """Raised when bootstrap steps fail."""


def print_step(message: str) -> None:
    print(f"[bootstrap] {message}")


def ensure_python(min_major: int = 3, min_minor: int = 11) -> None:
    version = sys.version_info
    if (version.major, version.minor) < (min_major, min_minor):
        raise BootstrapError(
            f"Python >= {min_major}.{min_minor} required; detected {version.major}.{version.minor}.{version.micro}"
        )
    print_step(f"Python {version.major}.{version.minor}.{version.micro} OK")


def create_or_refresh_venv(venv_dir: Path, python_exe: str, recreate: bool) -> Path:
    if recreate and venv_dir.exists():
        print_step(f"Removing existing virtual environment at {venv_dir}")
        shutil.rmtree(venv_dir)

    if venv_dir.exists():
        print_step(f"Using existing virtual environment at {venv_dir}")
    else:
        print_step(f"Creating virtual environment at {venv_dir}")
        subprocess.run([python_exe, "-m", "venv", str(venv_dir)], check=True)

    bin_dir = venv_dir / ("Scripts" if os.name == "nt" else "bin")
    python_path = bin_dir / ("python.exe" if os.name == "nt" else "python")
    pip_path = bin_dir / ("pip.exe" if os.name == "nt" else "pip")

    if not python_path.exists() or not pip_path.exists():
        raise BootstrapError(
            f"Virtual environment at {venv_dir} appears broken (missing python/pip)"
        )

    return python_path


def run_pip(python_in_venv: Path, arguments: list[str]) -> None:
    cmd = [str(python_in_venv), "-m", "pip"] + arguments
    print_step("Running: " + " ".join(cmd))
    subprocess.run(cmd, check=True)


def install_dependencies(python_in_venv: Path, upgrade: bool) -> None:
    run_pip(python_in_venv, ["install", "--upgrade", "pip", "setuptools", "wheel"])

    if REQUIREMENTS_FILE.exists():
        args = ["install", "-r", str(REQUIREMENTS_FILE)]
        if upgrade:
            args.insert(1, "--upgrade")
        run_pip(python_in_venv, args)
    else:
        print_step("requirements.txt not found; skipping dev dependency install")

    editable_args = ["install", "-e", str(REPO_ROOT)]
    if upgrade:
        editable_args.insert(1, "--upgrade")
    run_pip(python_in_venv, editable_args)


def ensure_env_file() -> None:
    if ENV_FILE.exists():
        print_step(f"Environment file already present at {ENV_FILE}")
        return

    print_step(f"Creating default environment file at {ENV_FILE}")
    ENV_FILE.write_text(DEFAULT_ENV_TEMPLATE, encoding="utf-8")


def ensure_config_file() -> None:
    if CONFIG_TARGET.exists():
        print_step(f"Config file already present at {CONFIG_TARGET}")
        return

    if CONFIG_EXAMPLE.exists():
        print_step(f"Copying config template to {CONFIG_TARGET}")
        shutil.copyfile(CONFIG_EXAMPLE, CONFIG_TARGET)
    else:
        print_step("No central.example.json found; skipping config copy")


def ensure_directories() -> None:
    for directory in RUNTIME_DIRECTORIES:
        if directory.exists():
            continue
        print_step(f"Creating directory {directory}")
        directory.mkdir(parents=True, exist_ok=True)


def summarize(python_in_venv: Path) -> None:
    bin_dir = python_in_venv.parent
    activate_hint = "activate"
    if os.name == "nt":
        activate_cmd = bin_dir / "activate.bat"
        activate_hint = f"{activate_cmd}"
    else:
        activate_cmd = f"source {bin_dir}/activate"
        activate_hint = activate_cmd

    print_step("Bootstrap complete.")
    print(
        dedent(
            f"""
            Next steps:
              1. Activate the virtualenv:
                 {activate_hint}
              2. Launch the CLI:
                 python main.py --stream
            """
        ).strip()
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Prepare a local development environment for noctics-core."
    )
    parser.add_argument(
        "--venv",
        type=Path,
        default=DEFAULT_VENV,
        help=f"Path to the virtual environment directory (default: {DEFAULT_VENV})",
    )
    parser.add_argument(
        "--python",
        default=sys.executable,
        help="Python interpreter to use for creating the virtual environment",
    )
    parser.add_argument(
        "--recreate",
        action="store_true",
        help="Recreate the virtual environment from scratch",
    )
    parser.add_argument(
        "--upgrade",
        action="store_true",
        help="Force dependency upgrades (passes --upgrade to pip installs)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    try:
        ensure_python()
        venv_python = create_or_refresh_venv(args.venv, args.python, args.recreate)
        install_dependencies(venv_python, args.upgrade)
        ensure_env_file()
        ensure_config_file()
        ensure_directories()
        summarize(venv_python)
    except (subprocess.CalledProcessError, BootstrapError) as exc:
        print_step(f"Bootstrap failed: {exc}")
        sys.exit(1)


if __name__ == "__main__":
    main()
